#!/bin/bash

build() {
    local mod

    add_module dm-crypt
    if [[ $CRYPTO_MODULES ]]; then
        for mod in $CRYPTO_MODULES; do
            add_module "$mod"
        done
    else
        add_all_modules '/crypto/'
    fi

    if [ -d "${BUILDROOT}/etc/initcpio/gpg" ]; then
        echo "WARNING! /etc/initcpio/gpg exists in initramfs buildroot, deleting." > 2
        rm -rf "${BUILDROOT}/etc/initcpio/gpg"
    fi

    mkdir -p "${BUILDROOT}/etc/initcpio/gpg"
    chmod 0700 "${BUILDROOT}/etc/initcpio/gpg"
    echo "pinentry-program /usr/bin/pinentry-tty" > "${BUILDROOT}/etc/initcpio/gpg/gpg-agent.conf"

    # DEBUG:
    echo "log-file /scdaemon.log" > ${BUILDROOT}/etc/initcpio/gpg/scdaemon.conf
    echo "verbose" >> ${BUILDROOT}/etc/initcpio/gpg/scdaemon.conf

    # You can adjust the reader port to your specific smartcard reader.
    # Find out the reader port by running `pcsc_scan` (needs the package "pcsc-tools").
    #echo "reader-port \"Broadcom Corp 5880 [Contacted SmartCard] (0123456789ABCD) 00 00\"" >> ${BUILDROOT}/etc/initcpio/gpg/scdaemon.conf

    add_file "/etc/keys/luks_key.gpg"
    add_file "/etc/keys/public_keys.asc"
    add_binary "cryptsetup"
    add_binary "dmsetup"
    add_binary "pcscd"
    add_binary "python"
    add_binary "pinentry-tty"

    add_binary "/etc/keys/gnupg-1.4/g10/gpg" "/usr/bin/gpg1"

    # Add all files from selected packages. The "grep" command selects the second column 
    for item in $(pacman --query --list ccid pcsclite libusb libbksba    libusb-compat flex | grep --only-matching ' .*$' ); do
	    if [ -f "$item" ]; then
		    echo "adding file $item"
		    add_file "$item"
	    fi
    done

    if [ -f /etc/private.gpg ]; then
        if ! gpg --homedir "${BUILDROOT}/etc/initcpio/gpg" --import /etc/private.gpg &> /dev/null; then
            echo "ERROR while importing private key file." >&2
        fi
    else
        echo "WARNING /etc/private.gpg not found." >&2
    fi

    add_runscript
}

help() {
    cat <<HELPEOF
This hook allows for an encrypted root device. Users should specify the device
to be unlocked using 'cryptdevice=device:dmname' on the kernel command line,
where 'device' is the path to the raw device, and 'dmname' is the name given to
the device after unlocking, and will be available as /dev/mapper/dmname.

For unlocking via keyfile, 'cryptkey=device:fstype:path' should be specified on
the kernel cmdline, where 'device' represents the raw block device where the key
exists, 'fstype' is the filesystem type of 'device' (or auto), and 'path' is
the absolute path of the keyfile within the device.

Without specifying a keyfile, you will be prompted for the password at runtime.
This means you must have a keyboard available to input it, and you may need
the keymap hook as well to ensure that the keyboard is using the layout you
expect.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
